### ISSUE TITLE
Getting a 500 internal error

### ISSUE THREAD

**Issue by kakumar** [speedtracker/speedtracker.org#3] opened 2016-10-24 20:10 UTC
I am trying to fire a test e2e and keeps getting 500 internal error..
https://speedtracker.org/test
can you please tell me how to debug this?

response headers
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=utf-8
Date: Mon, 24 Oct 2016 19:43:26 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=d71a022572395d6facdab21947df82b941477338206; expires=Tue, 24-Oct-17 19:43:26 GMT; path=/; domain=.speedtracker.org; HttpOnly
Via: 1.1 vegur
X-Firefox-Spdy: h2
cf-ray: 2f6feaed0f1a22a0-LAX
x-powered-by: Express

**Comment by eduardoboucas** [comment] 2016-10-24 21:19
I can't replicate this. Can you send me your info (GitHub username, repository and name of profile) to mail@eduardoboucas.com? Also, a screenshot would help.

Thanks.

**Comment by eduardoboucas** [comment] 2016-10-25 09:27
Duplicate of https://github.com/speedtracker/speedtracker/issues/13.

**Closed as completed by eduardoboucas** 2016-10-25 09:27 UTC
